rco-nodeca:
  contacts_default_email: support@rcopen.com

  # # email could be customized for each form, valid form names are:
  # # 'nick_change', 'support', 'mod_appeal', 'sales' and 'user_update'
  #
  #contacts:
  #  sales:
  #    # email or an array of emails to send filled forms to
  #    email: [ ... ]
