router:
  http.get:
    rcd-nodeca.contacts:
      "/contacts": ~

    rcd-nodeca.contacts.sales:
      "/contacts/sales": ~

    rcd-nodeca.contacts.support:
      "/contacts/support": ~

    rcd-nodeca.contacts.nick_change:
      "/contacts/nick_change": ~

    rcd-nodeca.contacts.user_update:
      "/contacts/user_update": ~

    rcd-nodeca.contacts.mod_appeal:
      "/contacts/mod_appeal": ~

    admin.rcd-nodeca.update_by_link:
      "/members/update_by_link/{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'
