recursive: true
public: true
type:
  widget_css:
    - "*.css"
    - "*.styl"
    - "*.scss"
  widget_i18n: i18n/*.yml
  widget_view:
    - "*.jade"
    - "*.pug"
  widget_js: "*.js"
  bin:
    - "rcd_logo/logo.svg"
