# for 'delete_inactive_users' cron task,
# group -> period after which users in that group
# can be removed (in days)
delete_inactive_users:
  incomplete_profile: 3
  just_registered: 3
  che: 7
  novices: 21
  members: 120
