search:
  searchd:
    log: searchd.log
    # query_log
    # query_log_min_msec: 100
    subtree_docs_cache: 10M
    subtree_hits_cache: 16M
    qcache_max_bytes: 16777216
    qcache_thresh_msec: 1000
    expansion_limit: 16
    # rt_merge_iops: 40
    # rt_merge_maxiosize: 1M
    attr_flush_period: 900
    queue_max_length: 1000

  common:
    lemmatizer_base: npm:rcd-nodeca/sphinx_dicts/lemmatizer

  indexes:
    _default:
      # try *_all
      morphology: lemmatize_en,lemmatize_ru,lemmatize_de
      stopwords: npm:rcd-nodeca/sphinx_dicts/stopwords.txt
      stopwords_unstemmed: 1
      # exceptions
      charset_table: 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+0435, U+451->U+0435
      ignore_chars: U+AD
      #min_stemming_len: 4
      #min_word_len: 1
      index_exact_words: 1
      blend_chars: +, &, U+23, ., @, -
      blend_mode: trim_none, trim_head, trim_tail, skip_pure
      # ? expand_keywords
      # ? rt_mem_limit

    'forum_posts : _default_content':
      rt_mem_limit: 1G
    'forum_topics : _default_content': {}
