search:
  indexes:
    default:
      morphology: lemmatize_en,lemmatize_ru,lemmatize_de
      charset_table: 0..9, _, english, russian
      ignore_chars: '-, U+AD'
      min_stemming_len: 4
      min_word_len: 1
      stopwords: rcd-nodeca/config/stopwords.txt
      wordforms: rcd-nodeca/config/wordforms.txt
